#!/usr/bin/env python3
"""Generate ARM64 steam_api64 flat-API wrappers that call into lsteamclient vtables."""
import re, glob, json, os, sys

if len(sys.argv) != 3:
    sys.exit('usage: gen.py <proton/lsteamclient dir> <output dir>')
LSC, OUT = sys.argv[1], sys.argv[2]
SDK = f'{LSC}/steamworks_sdk_161'
flat = open(f'{SDK}/steam_api_flat.h').read()

# flat methods: S_API <ret> SteamAPI_<ISteamX>_<Method>( <ISteamX>* self, ... );
decl_re = re.compile(r'^S_API (.+?)\s*\b(SteamAPI_(I[A-Za-z]+)_([A-Za-z0-9_]+))\(\s*(\3\s*\*\s*self)\s*(?:,\s*(.*?))?\s*\);', re.M)
methods = {}  # class -> list of (flatname, method, ret, params)
for m in decl_re.finditer(flat):
    ret, fname, cls, meth, _, params = m.groups()
    methods.setdefault(cls, []).append((fname, meth, ret.strip(), (params or '').strip()))

# lsteamclient vtables: winI<Class>_<VER>_vtables ... VTABLE_ADD_FUNC(winI<Class>_<VER>_<Method>)
vtables = {}  # (cls, ver) -> [method names]
for path in glob.glob(f'{LSC}/winI*.c'):
    src = open(path).read()
    for vm in re.finditer(r'__ASM_VTABLE\((winI[A-Za-z]+)_([A-Za-z0-9_]+?),\s*((?:\s*VTABLE_ADD_FUNC\([^)]*\))+)', src):
        cls, ver, body = vm.groups()
        names = re.findall(r'VTABLE_ADD_FUNC\(\w+?_' + re.escape(ver) + r'_(\w+)\)', body)
        vtables[(cls[3:] if cls.startswith('win') else cls, ver)] = names
    # functions with hidden return pointer
retptr = set()
for path in glob.glob(f'{LSC}/winI*.c'):
    for fm in re.finditer(r'__thiscall (winI\w+)\(struct w_iface \*_this, [^)]*?\*_ret[,)]', open(path).read()):
        retptr.add(fm.group(1))

# flat name -> lsteamclient method name, derived from STEAM_FLAT_NAME overloads in the SDK headers
overload = {}  # (cls, flatmeth) -> lsteamclient name
inline_only = set()
for hdr in glob.glob(f'{SDK}/*.h'):
    src = open(hdr, encoding="latin-1").read()
    for cm in re.finditer(r'\nclass (I\w+)\s*\n?\{(.*?)\n\};', src, re.S):
        cls, body = cm.groups()
        count = {}
        pending_flat = None
        for line in body.split('\n'):
            fm = re.search(r'STEAM_FLAT_NAME\(\s*(\w+)\s*\)', line)
            if fm: pending_flat = fm.group(1); continue
            vm = re.search(r'^\s*virtual\s+.*?\b(\w+)\s*\(', line)
            if vm:
                name = vm.group(1); count[name] = count.get(name, 0) + 1
                lname = name if count[name] == 1 else f'{name}_{count[name]}'
                overload[(cls, pending_flat or name)] = lname
                pending_flat = None
            elif re.search(r'^\s*(inline\s+)?[\w:<> *&]+\s+\**(\w+)\s*\(', line) and pending_flat is None:
                im = re.search(r'(\w+)\s*\(', line)
                inline_only.add((cls, im.group(1)))

VERSIONS = {
 'ISteamClient': 'SteamClient021', 'ISteamUser': 'SteamUser023', 'ISteamFriends': 'SteamFriends017',
 'ISteamUtils': 'SteamUtils010', 'ISteamMatchmaking': 'SteamMatchMaking009',
 'ISteamMatchmakingServers': 'SteamMatchMakingServers002', 'ISteamGameSearch': 'SteamMatchGameSearch001',
 'ISteamParties': 'SteamParties002', 'ISteamRemoteStorage': 'STEAMREMOTESTORAGE_INTERFACE_VERSION016',
 'ISteamUserStats': 'STEAMUSERSTATS_INTERFACE_VERSION013', 'ISteamApps': 'STEAMAPPS_INTERFACE_VERSION008',
 'ISteamNetworking': 'SteamNetworking006', 'ISteamScreenshots': 'STEAMSCREENSHOTS_INTERFACE_VERSION003',
 'ISteamMusic': 'STEAMMUSIC_INTERFACE_VERSION001', 'ISteamMusicRemote': 'STEAMMUSICREMOTE_INTERFACE_VERSION001',
 'ISteamHTTP': 'STEAMHTTP_INTERFACE_VERSION003', 'ISteamInput': 'SteamInput006',
 'ISteamController': 'SteamController008', 'ISteamUGC': 'STEAMUGC_INTERFACE_VERSION020',
 'ISteamHTMLSurface': 'STEAMHTMLSURFACE_INTERFACE_VERSION_005', 'ISteamInventory': 'STEAMINVENTORY_INTERFACE_V003',
 'ISteamTimeline': 'STEAMTIMELINE_INTERFACE_V004', 'ISteamVideo': 'STEAMVIDEO_INTERFACE_V007',
 'ISteamParentalSettings': 'STEAMPARENTALSETTINGS_INTERFACE_VERSION001',
 'ISteamRemotePlay': 'STEAMREMOTEPLAY_INTERFACE_VERSION002',
 'ISteamNetworkingMessages': 'SteamNetworkingMessages002', 'ISteamNetworkingSockets': 'SteamNetworkingSockets012',
 'ISteamNetworkingUtils': 'SteamNetworkingUtils004', 'ISteamGameServer': 'SteamGameServer015',
 'ISteamGameServerStats': 'SteamGameServerStats001', 'ISteamNetworkingFakeUDPPort': 'SteamNetworkingFakeUDPPort001',
}
out = ['/* Generated by gen.py - do not edit. */', '#include "steam_api_shim.h"', '']
report = {}
MANUAL = []
for cls, ms in methods.items():
    ver = VERSIONS.get(cls)
    if ver is None:
        # app-implemented interfaces (matchmaking responses): declaration order
        vt = [meth for _, meth, _, _ in ms]
    else:
        vt = vtables[(cls, ver)]
    report[cls] = ver
    for fname, meth, ret, params in ms:
        lname = overload.get((cls, meth), meth) if ver else meth
        if lname not in vt:
            MANUAL.append(fname)
            continue  # inline SDK helper, implemented in steam_api_helpers.cpp
        idx = vt.index(lname)
        wname = f'win{cls}_{ver}_{lname}'
        plist = [p.strip() for p in params.split(',')] if params else []
        # split "type name" -> name is last identifier
        pnames = [re.findall(r'(\w+)\s*$', p)[0] for p in plist]
        ptypes = [p[:p.rfind(n)].strip() for p, n in zip(plist, pnames)]
        args = ', '.join(pnames)
        # Games built against an older SDK ask for older interface versions; hand them ours.
        remap = '    pchVersion = shim_map_interface_version(pchVersion);\n' if cls == 'ISteamClient' and 'pchVersion' in pnames else ''
        if remap:
            out.append(f'S_API {ret} {fname}( {cls}* self{", " + params if params else ""} )\n'
                       f'{{\n    SHIM_TRACE("{fname}");\n{remap}    return (({ret} (*)({", ".join(["void *"] + ptypes)}))VTBL(self)[{idx}])(self{", " + args if args else ""});\n}}\n')
            continue
        if wname in retptr:
            fp = ', '.join(['void *', f'{ret} *'] + ptypes)
            out.append(f'S_API {ret} {fname}( {cls}* self{", " + params if params else ""} )\n'
                       f'{{\n    SHIM_TRACE("{fname}");\n    {ret} r;\n    ((void (*)({fp}))VTBL(self)[{idx}])(self, &r{", " + args if args else ""});\n    return r;\n}}\n')
        else:
            fp = ', '.join(['void *'] + ptypes)
            out.append(f'S_API {ret} {fname}( {cls}* self{", " + params if params else ""} )\n'
                       f'{{\n    SHIM_TRACE("{fname}");\n    return (({ret} (*)({fp}))VTBL(self)[{idx}])(self{", " + args if args else ""});\n}}\n')

# Interface versions this shim implements, for shim_map_interface_version()
out.append('extern const char *const shim_interface_versions[] = {')
out += [f'    "{v}",' for v in sorted(set(VERSIONS.values()))]
out.append('    NULL,\n};\n')

# GetISteamGenericInterface without the version mapping, for the legacy interfaces below
gi = vtables[('ISteamClient', VERSIONS['ISteamClient'])].index('GetISteamGenericInterface')
out.append('void *shim_raw_generic_interface( ISteamClient* self, HSteamUser hSteamUser, HSteamPipe hSteamPipe, const char * pchVersion )\n'
           f'{{\n    return ((void * (*)(void *, HSteamUser, HSteamPipe, const char *))VTBL(self)[{gi}])(self, hSteamUser, hSteamPipe, pchVersion);\n}}\n')

# Flat functions of older SDKs that this SDK dropped. They call lsteamclient's own
# implementation of the old interface version, so Steam still answers them.
#   (flat name, interface, version, method, return type, params after self, object)
# object 'self': the caller passes the old interface itself (we don't map it to anything);
# object 'legacy': the caller's object is our newer version; use the old one for this call.
LEGACY = [
    ('SteamAPI_ISteamUserStats_RequestCurrentStats', 'ISteamUserStats', 'STEAMUSERSTATS_INTERFACE_VERSION012',
     'RequestCurrentStats', 'bool', '', 'legacy'),
    ('SteamAPI_ISteamAppList_GetNumInstalledApps', 'ISteamAppList', 'STEAMAPPLIST_INTERFACE_VERSION001',
     'GetNumInstalledApps', 'uint32', '', 'self'),
    ('SteamAPI_ISteamAppList_GetInstalledApps', 'ISteamAppList', 'STEAMAPPLIST_INTERFACE_VERSION001',
     'GetInstalledApps', 'uint32', 'AppId_t * pvecAppID, uint32 unMaxAppIDs', 'self'),
    ('SteamAPI_ISteamAppList_GetAppName', 'ISteamAppList', 'STEAMAPPLIST_INTERFACE_VERSION001',
     'GetAppName', 'int', 'AppId_t nAppID, char * pchName, int cchNameMax', 'self'),
    ('SteamAPI_ISteamAppList_GetAppInstallDir', 'ISteamAppList', 'STEAMAPPLIST_INTERFACE_VERSION001',
     'GetAppInstallDir', 'int', 'AppId_t nAppID, char * pchDirectory, int cchNameMax', 'self'),
    ('SteamAPI_ISteamAppList_GetAppBuildId', 'ISteamAppList', 'STEAMAPPLIST_INTERFACE_VERSION001',
     'GetAppBuildId', 'int', 'AppId_t nAppID', 'self'),
]
for fname, cls, ver, meth, ret, params, obj in LEGACY:
    idx = vtables[(cls, ver)].index(meth)
    plist = [p.strip() for p in params.split(',')] if params else []
    pnames = [re.findall(r'(\w+)\s*$', p)[0] for p in plist]
    ptypes = [p[:p.rfind(n)].strip() for p, n in zip(plist, pnames)]
    target = 'self' if obj == 'self' else f'shim_legacy_user_interface("{ver}")'
    fail = '0' if ret != 'bool' else 'false'
    out.append(f'S_API {ret} {fname}( void* self{", " + params if params else ""} )\n'
               f'{{\n    SHIM_TRACE("{fname}");\n    void *obj = {target};\n    if (!obj) return {fail};\n'
               f'    return (({ret} (*)({", ".join(["void *"] + ptypes)}))VTBL(obj)[{idx}])(obj{", " + ", ".join(pnames) if pnames else ""});\n}}\n')
open(os.path.join(OUT, 'flat_generated.cpp'), 'w').write('\n'.join(out))
json.dump(report, open(os.path.join(OUT, 'versions.json'), 'w'), indent=1)
open(os.path.join(OUT, 'manual.txt'), 'w').write('\n'.join(MANUAL)+'\n')
print(len(report), 'interfaces;', len(MANUAL), 'hand-written helpers;', sum(len(v) for v in methods.values()), 'methods;', len(retptr), 'retptr funcs total')
